# command to run:
# docker-compose -f docker-compose-dev-hot.yml up

version: "3"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: allisons11/cbd-client
    container_name: cdb-client-dev
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: allisons11/cdb-client
    container_name: cdb-server-dev
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app/server
      - /app/server/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev

# shared volumes for development
volumes:
  node_modules:
